### ISSUE TITLE
Repeating wave

### ISSUE THREAD

**Issue by Zulex** [bobbykaz/spatial-mapping-shaders#1]
Looks great! 

But is there a way to make the effect repeat itself? I tried to look in the shader script but couldnt find anything.

Thanks!

**Comment by bobbykaz** [comment]
Thanks for the interest!
I added a property to the RippleWave shader that lets the ripple effect repeat. You can also check out the diff to get an idea.

Is this along the lines of what you were looking for?

**Comment by bobbykaz** [comment]
Let me know if my addition didn't meet what you expected.
